version: '3.8'

services:
  integrator:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: legacy_integrator_service
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - pricing
    depends_on:
      - db

  db:
    restart: always
    image: postgres:11.7
    container_name: legacy_integrator_db
    environment:
      - POSTGRES_USER=solfacil
      - POSTGRES_PASSWORD=solfacil
      - POSTGRES_DB=solfacil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - pricing

networks:
  pricing:
    external: true

volumes:
  postgres_data:
  django-service:
  static_volume:
