name: Build ArgoCD application
on:
  push:
    branches:
      - feature/devops3
#on: 
#  workflow_dispatch:
#    inputs:
#      app_name:
#        type: string
#        default: 'legacy-integrator'        
#      env:
#        type: choice
#        description: Environment name?
#        options: 
#        - stg
#        - prod
#        - hml
jobs:  
  stg:
    uses: solfacil/github-actions-workflows/.github/workflows/DockerBuildAndPush.yml@main
    if: ${{ github.event.inputs.env == 'stg' }} 
    with:
      env: ${{ github.event.inputs.env }}
      app_name: ${{ github.event.inputs.app_name }}
    secrets: inherit
  prod:
    uses: solfacil/github-actions-workflows/.github/workflows/DockerBuildAndPush.yml@main
    if: ${{ github.event.inputs.env == 'prod' }} 
    with:
      env: ${{ github.event.inputs.env }}
      app_name: ${{ github.event.inputs.app_name }}
    secrets: inherit
