name: "Passcheck"

on: 
  pull_request:

jobs:
  passcheck:
    runs-on: k8s-runner

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: solfacil_local_dev
          POSTGRES_USER: solfacil_local_dev
          POSTGRES_DB: solfacil_local_dev
        ports:
          - 5432:5432

    defaults:
      run:
        shell: nix develop --command bash {0}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Poetry install
        run: |
          poetry install
      - name: Run Tests
        run: |
          poetry run pytest

      
  
